### ISSUE TITLE
OGP is generating loads of errors in the Geeklog error log

### ISSUE THREAD

**Issue by jrmain** [Geeklog-Plugins/ogp#2]
Since I started using OGP, I'm seeing TONS of these error messages in the Geeklog error log:
	"OGP: Error!  Facebook AppID is not set."

	"OGP: Error!  You have to set either your Facebook User ID(s) or your Facebook App ID first 
	at the configuration panel!"

I get bursts of about ten per second at times, and hundreds every day.
I have set my Facebook User ID, so the error makes no sense.

**Comment by mystralkk** [comment]
Fixed with changeset c3ed670.  Please try v1.1.9 (no database change)

**Comment by jrmain** [comment]
Installed the new version 1.1.9 files, updated to the new version in the plugins list, and confirmed that the new version is running. Any time I go to a specific story/article, I get eight "OGP: Error!  Facebook AppID is not set." messages in error.log.

**Comment by mystralkk** [comment]
I changed some code of functions.inc.   Give it another try.

**Comment by jrmain** [comment]
That seems to have fixed the problem. Thanks.

**Comment by jrmain** [comment]
I spoke too soon. The log entries started up again on 2017 Mar 29 at 05:00:16.
