### ISSUE TITLE
OGP getimagesize errors cause 403 errors on affected pages

### ISSUE THREAD

**Issue by jrmain** [Geeklog-Plugins/ogp#4]
Some pages that include off-site images are throwing errors like this:
E_WARNING(2) - getimagesize(https://superuser.com/users/flair/41423.png): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden @ /var/[snip]/plugins/ogp/functions.inc line 327

These pages also cause 403 errors in the browser.

Disabling the OGP plugin makes the errors go away.

I was able to fix the problem by commenting out the offending line in functions.inc (327). Doing this doesn't seem to have caused any other problems, and the Facebook sharing debugger shows that images seem to be handled fine in FB posts, including the default image.

Running OGP plugin 1.2.2.

**Comment by mystralkk** [comment]
Thanks for your report.  I fixed the issue and updated the plugin to v1.2.3.

**Comment by jrmain** [comment]
I updated OGP manually to version 1.2.3, and the problem does seem to be resolved. Thanks!

**Comment by mystralkk** [comment]
I'm glad to hear that.  Have fun!
